### PR TITLE
fix: save into cache under 304 response

### LINKED ISSUE #42: Header "if-none-match" causes server side re-rendering
I found that when the browser provides request header "if-none-match" with etag value same as the generated content, cacheable-response doesn't save the response in cache after expired.
This causes the server executes SSR on every request because cacheable-response doesn't save the response cache.

Should the cache saving block https://github.com/Kikobeats/cacheable-response/blob/55eca7ad79d3b78bb1fdc6740be46a17edc18dc6/index.js#L123-L127 being place before the 304 response block https://github.com/Kikobeats/cacheable-response/blob/55eca7ad79d3b78bb1fdc6740be46a17edc18dc6/index.js#L117-L121 ?

### PR DESCRIPTION
**Pull request by iKoala**
resolve #42 

Save cache before send response code 304.

### CODE REVIEW

**Comment by Kikobeats** [comment]
Thanks for that @iKoala 

I feel a bit risky merge this without tests, so @sarneeh's opinion about this change (since it's the original code author) is very appreciated 🙂

**Comment by sarneeh** [comment]
@iKoala is correct. I missed this case in my implementation 😶

**Comment by iKoala** [comment]
> Thanks for that @iKoala
> 
> I feel a bit risky merge this without tests, so @sarneeh's opinion about this change (since it's the original code author) is very appreciated 🙂

@Kikobeats I agree there should be a test case for this issue but sadly I am not familiar with your testing flow (I got import error when running the test.) If you can give me some hints on how to setup the test flow, I can create a test case for this issue.

**Comment by Kikobeats** [comment]
@iKoala 

if you clone the repo locally, just need to perform an `npm install` and after that a `npm test` for running all the tests.

For adding a new test, go here
https://github.com/Kikobeats/cacheable-response/blob/master/test/index.js#L241

copy/paste the last test and add it following the shame shape 🙂

**Comment by iKoala** [comment]
@Kikobeats 

Actually I did the same for testing but I got the following errors:

```
import { AssertionError } from 'assert'
  ^^^^^^

  SyntaxError: Cannot use import statement outside a module
```

It seems that the import syntax not supported by native node (Node Version v13.9.0)

**Comment by sarneeh** [comment]
All the devDependencies are set to `latest`. Ava got updated to 3.0 and it's not working anymore. Current code works on 2.x.

https://github.com/Kikobeats/cacheable-response/blob/55eca7ad79d3b78bb1fdc6740be46a17edc18dc6/package.json#L56-L78

@Kikobeats It's not a good practice to set dependencies to `latest`. Major version updates mostly end up with breaking changes which require the users to change the code. Better to change it to a version range.

**Comment by iKoala** [comment]
@sarneeh 
Thanks for for information, I successfully ran the test case now by reinstalling `npm rm ava --save-dev && npm install ava@2 --save-dev`

@Kikobeats 
I also agree with @sarneeh , you shouldn't use `latest` version tag for dependencies even they are only dev dependency, you will not know when will they break your project with major updates. You may also want to commit `package-lock.json` to lock the dependency versions.

File: test/index.js [hunk 1]
```diff
@@ -259,3 +260,28 @@ test('return empty 304 response when If-None-Match matches ETag', async t => {
   t.is(statusCode, 304)
   t.is(body, '')
 })
+
+test('return HIT after empty 304 response', async t => {
```
Comment (sarneeh) [inline test/index.js]: Not sure if this test checks what it should. I think that when you'll remove the implementation, this test will still pass.

Comment (iKoala) [reply test/index.js]: Actually the test would fail before the implementation. I have already tested with both `master` branch and this `master-fix-response-304-cache` branch.

Scenario before implementation (performance issue):
1. Browser send request with header `if-none-match`
2. Cache expired and server does SSR
3. Etag value is the same and content not modified
4. **Server response 304 with empty body and generated content is not saved in cache store**
* This behaviour will cause the server does SSR on subsequent request because cached data is not saved in cache store and cacheable-response is supposed to save the cached data in cache store before sending 304 response

Scenario after implementation:
1. Browser send request with header `if-none-match`
2. Cache expired and server does SSR
3. Etag value is the same and content not modified
4. **Generated content is saved to cache store before response 304 with empty body**
* Now the SSR generated content is saved in cache store and any subsequent request will use the cached data instead of generating the content again before it expires.

What the test does?
1. First request to generate cached data
2. Clear the cache store (simulate cache expiry)
3. Send second request with `if-none-match` and Etag value from first request, server would response 304 not modified
4. Send third request without header `if-none-match` and server should return cached data with `HIT` cache status (server response `MISS` status before implementation which would cause the test case fails)

I found this problem in my Next.js project in production environment because our content is mostly static with the same Etag and I found that cacheable-response didn't save the SSR generated content and caused it to execute SSR more frequently than expected.

Comment (sarneeh) [reply test/index.js]: Okay, that makes sense. 

But the problem that I see here is that the test doesn't specifically test what you're trying to accomplish (which is not calling the `get` method when the response is 304). Returning `HIT` after empty 304 response doesn't indicate that your server would not rerender in this case. Does that make sense to you?

Comment (sarneeh) [reply test/index.js]: What I'd propose is to create a test spy as the `get` method and check if it isn't invoked on a 304 response.

Comment (Kikobeats) [reply test/index.js]: test

Comment (Kikobeats) [reply test/index.js]: @sarneeh could be this helpful for creating the spy? 

https://github.com/jamiebuilds/ninos

Comment (iKoala) [reply test/index.js]: Yes, I agree with you the test case doesn't cover the actual behaviour.
However, I think it does still make sense to test if the cacheable-response returning `HIT` instead of `MISS` after empty 304 response because re-render did happen before empty 304 response.
We can assume that the server doesn't re-render when returning `HIT` because there is another test case `HIT for second access` which is using the same theory to test the lib.

Like you said, we may need to expand the test suite if we really want to test the actual server re-rendering.

Comment (sarneeh) [reply test/index.js]: @iKoala That makes total sense! Let's merge this!
